name: Simon & TrustFlow team
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  demo_evidence:
    environment: ProductDemo
    runs-on: ubuntu-latest
    name: simon's evidence demo

    
    steps:
      - name: Install jfrog cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
          
      - name: create predicate
        run: |
          echo ${{vars.ARTIFACTORY_URL}}
          JSON_DATA='{"name":"GitHub Actions"}'
          echo "$JSON_DATA" > predicate.json
        
      - name: debug folder
        run: |
          ls -lta
          cat predicate.json
          
      - name: create evidence on package
        run: |
          jf evd create --predicate predicate.json \
          --predicate-type simon3 --package-name hello-world \
          --package-version simon --package-repo-name example-project-docker-dev-local \
          --key "${{ secrets.PRIVATE_KEY }}"

      - name: create evidence on release bundle
        run: |
          jf evd create --predicate predicate.json \
          --predicate-type simon3 --release-bundle simon --release-bundle-version 1.2.3 \
          --key "${{ secrets.PRIVATE_KEY }}"
  
