name: Simon & Yevdo team work!!!
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  demo_evidence:
    environment: ProductDemo
    runs-on: ubuntu-latest
    name: simon's evidence demo
    steps:
      - name: print hey
        run: echo ${{vars.ARTIFACTORY_URL}}
          JSON_DATA='{"name":"GitHub Actions"}'
          echo "$JSON_DATA" > output.json
          jf evd create --key ${{ secrets.PRIVATE_KEY }} --predicate output.json --predicate-type simon3 --package-name hello-world --package-version simon --package-repo-name example-project-docker-dev-local
  
