name: Simon & Yevdo team work!!!
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  demo_evidence:
    runs-on: ubuntu-latest
    name: simon's evidence demo
    steps:
      - name: print hey
        run: echo ${{vars.ARTIFACTORY_URL}}
  
